version: '3.8'
services:
  postgres_db:
    image: postgres:${POSTGRES_VERSION}
    container_name: to-do-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - to-do-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: to-do-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - to-do-network
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./log:/app/logs
